<a href="https://colab.research.google.com/github/KashyapTimbadiya/CE146_ML_Labs/blob/main/ML_Lab07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.1 Implement Logistic Regression Algorithm on the given dataset**

In [ ]:
#Importing libraries
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt

In [ ]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer (2).csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
#Declare label as last column in the source file
label = data.iloc[:, -1].values

print(label)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [ ]:
#Declaring X as all columns excluding last
X = data.iloc[:, :-1].values

print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,label,test_size=0.1, random_state=0)

In [ ]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train)
print(X_test)

[[-1.05714987  0.53420426]
 [ 0.2798728  -0.51764734]
 [-1.05714987  0.41733186]
 [-0.29313691 -1.45262654]
 [ 0.47087604  1.23543867]
 [-1.05714987 -0.34233874]
 [-0.10213368  0.30045946]
 [ 1.33039061  0.59264046]
 [-1.15265148 -1.16044554]
 [ 1.04388575  0.47576806]
 [ 1.8078987   1.52761967]
 [-0.38863853 -1.30653604]
 [-0.29313691 -0.37155684]
 [-0.38863853  1.32309297]
 [ 1.99890194  0.53420426]
 [ 0.66187928 -1.10200934]
 [-0.86614663  0.38811376]
 [-1.15265148  0.30045946]
 [ 1.04388575 -1.21888174]
 [-1.43915634 -1.45262654]
 [-0.57964177 -1.51106275]
 [ 2.09440356 -0.80982834]
 [-1.82116282  0.18358706]
 [-0.19763529  0.85560337]
 [-1.82116282 -1.27731794]
 [ 2.09440356  0.38811376]
 [-1.34365472  0.56342236]
 [-1.05714987 -0.34233874]
 [ 0.18437118 -0.66373784]
 [ 0.37537442  0.00827846]
 [-0.57964177  2.34572647]
 [-0.29313691  0.21280516]
 [-1.53465796 -0.19624824]
 [ 0.66187928 -1.39419034]
 [-1.05714987  0.56342236]
 [-1.91666444  0.35889566]
 [ 0.37537442  0.27124136]
 

In [ ]:
def standardize(X_tr):
    for i in range(shape(X_tr)[1]):
        X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])

In [ ]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

In [ ]:
from numpy import log,dot,exp,shape
class LogidticRegression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.1,iter=3000):
        weights,X = self.initialize(X)
        def cost(theta):
            z = dot(X,theta)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

In [ ]:
standardize(X_train)
standardize(X_test)
obj1 = LogidticRegression()

In [ ]:
print(X_train)
print(y_train)
model= obj1.fit(X_train,y_train)
y_pred = obj1.predict(X_test)
y_tr = obj1.predict(X_train)

[[-1.05714987  0.53420426]
 [ 0.2798728  -0.51764734]
 [-1.05714987  0.41733186]
 [-0.29313691 -1.45262654]
 [ 0.47087604  1.23543867]
 [-1.05714987 -0.34233874]
 [-0.10213368  0.30045946]
 [ 1.33039061  0.59264046]
 [-1.15265148 -1.16044554]
 [ 1.04388575  0.47576806]
 [ 1.8078987   1.52761967]
 [-0.38863853 -1.30653604]
 [-0.29313691 -0.37155684]
 [-0.38863853  1.32309297]
 [ 1.99890194  0.53420426]
 [ 0.66187928 -1.10200934]
 [-0.86614663  0.38811376]
 [-1.15265148  0.30045946]
 [ 1.04388575 -1.21888174]
 [-1.43915634 -1.45262654]
 [-0.57964177 -1.51106275]
 [ 2.09440356 -0.80982834]
 [-1.82116282  0.18358706]
 [-0.19763529  0.85560337]
 [-1.82116282 -1.27731794]
 [ 2.09440356  0.38811376]
 [-1.34365472  0.56342236]
 [-1.05714987 -0.34233874]
 [ 0.18437118 -0.66373784]
 [ 0.37537442  0.00827846]
 [-0.57964177  2.34572647]
 [-0.29313691  0.21280516]
 [-1.53465796 -0.19624824]
 [ 0.66187928 -1.39419034]
 [-1.05714987  0.56342236]
 [-1.91666444  0.35889566]
 [ 0.37537442  0.27124136]
 

In [ ]:
f1_score_tr = F1_score(y_train,y_tr)
f1_score_te = F1_score(y_test,y_pred)
print(f1_score_tr)
print(f1_score_te)

0.7521865889212829
0.5517241379310345


# **3.1 Using sklearn LogisticRegression model**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
LR = LogisticRegression(random_state = 0)
LR.fit(X_train,y_train)
y_pred=LR.predict(X_test)
print(f1_score(y_test,y_pred))

0.8


# **Exercise**

In [ ]:
#Importing libraries
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt

In [ ]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer (3).csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,label,test_size=0.1, random_state=146)

In [ ]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train)
print(X_test)

[[ 1.20414457e-01  5.69815867e-02]
 [ 1.20414457e-01  5.69815867e-02]
 [ 1.86993393e+00 -1.27505550e+00]
 [ 3.14805509e-01 -5.05434074e-01]
 [-1.53190949e+00 -1.24545468e+00]
 [ 8.00783139e-01 -1.09745056e+00]
 [ 1.28676077e+00  1.92183351e+00]
 [ 6.06392087e-01  2.06983763e+00]
 [ 7.03587613e-01 -7.12639843e-01]
 [ 1.18956524e+00 -1.45266045e+00]
 [-1.71172121e-01  2.21784176e+00]
 [ 5.09196561e-01  1.77382939e+00]
 [-2.68367647e-01 -9.19845613e-01]
 [-1.43471396e+00  3.82590653e-01]
 [-2.68367647e-01 -7.42240668e-01]
 [ 1.09236972e+00 -1.21585386e+00]
 [ 9.95174191e-01  6.19397247e-01]
 [ 2.17609983e-01 -3.57429953e-01]
 [-1.71172121e-01  1.65542610e+00]
 [-7.54345277e-01  2.93788181e-01]
 [-8.51540803e-01 -6.53438195e-01]
 [-1.53190949e+00 -1.79825007e-01]
 [-1.14312738e+00 -1.00864809e+00]
 [-2.68367647e-01 -2.98228304e-01]
 [-8.51540803e-01  3.23389005e-01]
 [ 1.57834735e+00 -1.27505550e+00]
 [-9.48736329e-01 -2.98228304e-01]
 [ 1.20414457e-01  2.34586532e-01]
 [-7.39765948e-02  2

In [ ]:
def standardize(X_tr):
    for i in range(shape(X_tr)[1]):
        X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])

In [ ]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    accuracy = (tp+tn)/(tp+tn+fp+fn)
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score, precision, recall, accuracy

In [ ]:
from numpy import log,dot,exp,shape
class LogidticRegression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.1,iter=100):
        weights,X = self.initialize(X)
        def cost(theta):
            z = dot(X,theta)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

In [ ]:
standardize(X_train)
standardize(X_test)
obj1 = LogidticRegression()

In [ ]:
#print(X_train)
#print(y_train)
print("*************")
model= obj1.fit(X_train,y_train)
print(sum(model))
print("**************")

y_pred = obj1.predict(X_test)
y_tr = obj1.predict(X_train)

*************
84.28090100129191
**************


In [ ]:

(f1_score_test,precision_test,recall_test,accuracy_test) = F1_score(y_test,y_pred)

print(f1_score_test,precision_test,recall_test,accuracy_test)

0.7567567567567568 0.6086956521739131 1.0 0.775


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
LR = LogisticRegression(random_state = 146)
LR.fit(X_train,y_train)
y_pred=LR.predict(X_test)
print(f1_score(y_test,y_pred))

0.7407407407407408
