<a href="https://colab.research.google.com/github/KashyapTimbadiya/CE146_ML_Labs/blob/main/ML_Lab04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **3.1 Problem Statement**

We’ll create a model that predicts crop yeilds for apples (target variable) by looking at the average tempera-
ture, rainfall and humidity (input variables or features) in different regions.

In [ ]:
import numpy as np
import torch
# Input (temp, rainfall, humidity)
inputs = np.array([[70, 34, 45], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [ ]:
# Targets (apples)
targets = np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 70.,  34.,  45.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# **3.2 Linear Regression Model (from scratch)**

In [ ]:
# Weights and biases
w = torch.randn(3, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(w)
print(b)

tensor([[ 0.2112],
        [ 0.6363],
        [-0.2283]], requires_grad=True)
tensor([0.4628], requires_grad=True)


In [ ]:
# Define the model
def model(x):
    return x @ w + b

In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[26.6090],
        [61.0686],
        [90.8648],
        [40.9207],
        [60.1430]], grad_fn=<AddBackward0>)


In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


# **3.3 Loss Function**

In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(849.4793, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward(retain_graph=True)

# **3.4 Compute Gradients**

In [ ]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.2112],
        [ 0.6363],
        [-0.2283]], requires_grad=True)
tensor([[-2938.4434],
        [-3929.6216],
        [-2611.9875]])


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0.],
        [0.],
        [0.]])
tensor([0.])


# **3.5 Adjust weights and biases using gradient descent**

In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[26.6090],
        [61.0686],
        [90.8648],
        [40.9207],
        [60.1430]], grad_fn=<AddBackward0>)


In [ ]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(849.4793, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-2938.4434],
        [-3929.6216],
        [-2611.9875]])
tensor([-40.5575])


In [ ]:
# Adjust weights & reset gradients
# alpha = 1e-5 / 0.1/0.0000001
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[ 0.2406],
        [ 0.6756],
        [-0.2022]], requires_grad=True)
tensor([0.4632], requires_grad=True)


In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)
print(preds)

tensor(592.3004, grad_fn=<DivBackward0>)
tensor([[ 31.1778],
        [ 68.8727],
        [100.2023],
        [ 46.5745],
        [ 67.7718]], grad_fn=<AddBackward0>)


# **3.6 Train for multiple epochs**

In [ ]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)
print(w)
print(b)


tensor(186.5546, grad_fn=<DivBackward0>)
tensor([[-0.0124],
        [ 0.8522],
        [ 0.1686]], requires_grad=True)
tensor([-0.2575], requires_grad=True)


In [ ]:
# Predictions
preds

tensor([[ 35.4368],
        [ 84.3985],
        [122.6377],
        [ 41.3620],
        [ 92.4997]], grad_fn=<AddBackward0>)

In [ ]:
# Targets
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])

# **Exercise **

In [1]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from torchvision.models import resnet18 as model

inputs = np.array(
    [[73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]], 
  dtype='float32')

targets = np.array([[56.],[81.],[119.],[22.],[103.]])


w=[[1.],[1.],[1.]]
b=[[2.],[2.],[2.],[2.],[2.]]

# learningRate=0.1
# 0.0001 -> output 0.51404101946832146
learningRate=0.0000001

iterations=1000

m=len(inputs)*1.0

weights=torch.tensor(w, requires_grad=True)
bias=torch.tensor(b, requires_grad=True)


finalLoss=0.0

for _ in range(iterations):
  weights=torch.tensor(weights,requires_grad=True)
  bias=torch.tensor(bias,requires_grad=True)

  inputs1=torch.tensor(inputs,requires_grad=False)
  y1=torch.tensor(targets)
  
  hypo=torch.matmul(inputs1,weights)+bias
  loss=((hypo-y1)**2)
  
  myloss=0.0

  for row in loss:
    myloss+=row[0]
  myloss/=2*m
  myloss.backward()
  # print("myloss : ",myloss)
  
  weights=weights-((weights.grad)*learningRate)
  bias=bias-((bias.grad)*learningRate)

  finalLoss=myloss.item()
print("finalLoss : ",finalLoss)
print("weights : ",weights)
print("bias : ",bias)


<ipython-input-1-cbaec189b95b>:36: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  weights=torch.tensor(weights,requires_grad=True)
<ipython-input-1-cbaec189b95b>:37: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  bias=torch.tensor(bias,requires_grad=True)


finalLoss :  557.7165998312354
weights :  tensor([[0.3797],
        [0.4181],
        [0.6227]], grad_fn=<SubBackward0>)
bias :  tensor([[1.9987],
        [1.9984],
        [1.9987],
        [1.9981],
        [1.9989]], grad_fn=<SubBackward0>)
